baseurl: /singapore
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: singapore
github_org: maptime
maptime:
  chapter: MaptimeSG
  twitter: MaptimeSG
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
